// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CameraRecenteringEntryT struct {
	MinimumAngle float32 `json:"minimum_angle"`
	MaximumAngle float32 `json:"maximum_angle"`
	WaitTime float32 `json:"wait_time"`
	RecenteringTime float32 `json:"recentering_time"`
}

func (t *CameraRecenteringEntryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	CameraRecenteringEntryStart(builder)
	CameraRecenteringEntryAddMinimumAngle(builder, t.MinimumAngle)
	CameraRecenteringEntryAddMaximumAngle(builder, t.MaximumAngle)
	CameraRecenteringEntryAddWaitTime(builder, t.WaitTime)
	CameraRecenteringEntryAddRecenteringTime(builder, t.RecenteringTime)
	return CameraRecenteringEntryEnd(builder)
}

func (rcv *CameraRecenteringEntry) UnPackTo(t *CameraRecenteringEntryT) {
	t.MinimumAngle = rcv.MinimumAngle()
	t.MaximumAngle = rcv.MaximumAngle()
	t.WaitTime = rcv.WaitTime()
	t.RecenteringTime = rcv.RecenteringTime()
}

func (rcv *CameraRecenteringEntry) UnPack() *CameraRecenteringEntryT {
	if rcv == nil {
		return nil
	}
	t := &CameraRecenteringEntryT{}
	rcv.UnPackTo(t)
	return t
}

type CameraRecenteringEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsCameraRecenteringEntry(buf []byte, offset flatbuffers.UOffsetT) *CameraRecenteringEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CameraRecenteringEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishCameraRecenteringEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCameraRecenteringEntry(buf []byte, offset flatbuffers.UOffsetT) *CameraRecenteringEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CameraRecenteringEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCameraRecenteringEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CameraRecenteringEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CameraRecenteringEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CameraRecenteringEntry) MinimumAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CameraRecenteringEntry) MutateMinimumAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *CameraRecenteringEntry) MaximumAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CameraRecenteringEntry) MutateMaximumAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *CameraRecenteringEntry) WaitTime() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CameraRecenteringEntry) MutateWaitTime(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *CameraRecenteringEntry) RecenteringTime() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CameraRecenteringEntry) MutateRecenteringTime(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func CameraRecenteringEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func CameraRecenteringEntryAddMinimumAngle(builder *flatbuffers.Builder, minimumAngle float32) {
	builder.PrependFloat32Slot(0, minimumAngle, 0.0)
}
func CameraRecenteringEntryAddMaximumAngle(builder *flatbuffers.Builder, maximumAngle float32) {
	builder.PrependFloat32Slot(1, maximumAngle, 0.0)
}
func CameraRecenteringEntryAddWaitTime(builder *flatbuffers.Builder, waitTime float32) {
	builder.PrependFloat32Slot(2, waitTime, 0.0)
}
func CameraRecenteringEntryAddRecenteringTime(builder *flatbuffers.Builder, recenteringTime float32) {
	builder.PrependFloat32Slot(3, recenteringTime, 0.0)
}
func CameraRecenteringEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
