// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CurveMsgT struct {
	T []float64 `json:"t"`
	V []float64 `json:"v"`
}

func (t *CurveMsgT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tOffset := flatbuffers.UOffsetT(0)
	if t.T != nil {
		tLength := len(t.T)
		CurveMsgStartTVector(builder, tLength)
		for j := tLength - 1; j >= 0; j-- {
			builder.PrependFloat64(t.T[j])
		}
		tOffset = builder.EndVector(tLength)
	}
	vOffset := flatbuffers.UOffsetT(0)
	if t.V != nil {
		vLength := len(t.V)
		CurveMsgStartVVector(builder, vLength)
		for j := vLength - 1; j >= 0; j-- {
			builder.PrependFloat64(t.V[j])
		}
		vOffset = builder.EndVector(vLength)
	}
	CurveMsgStart(builder)
	CurveMsgAddT(builder, tOffset)
	CurveMsgAddV(builder, vOffset)
	return CurveMsgEnd(builder)
}

func (rcv *CurveMsg) UnPackTo(t *CurveMsgT) {
	tLength := rcv.TLength()
	t.T = make([]float64, tLength)
	for j := 0; j < tLength; j++ {
		t.T[j] = rcv.T(j)
	}
	vLength := rcv.VLength()
	t.V = make([]float64, vLength)
	for j := 0; j < vLength; j++ {
		t.V[j] = rcv.V(j)
	}
}

func (rcv *CurveMsg) UnPack() *CurveMsgT {
	if rcv == nil {
		return nil
	}
	t := &CurveMsgT{}
	rcv.UnPackTo(t)
	return t
}

type CurveMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsCurveMsg(buf []byte, offset flatbuffers.UOffsetT) *CurveMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CurveMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishCurveMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCurveMsg(buf []byte, offset flatbuffers.UOffsetT) *CurveMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CurveMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCurveMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CurveMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CurveMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CurveMsg) T(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *CurveMsg) TLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CurveMsg) MutateT(j int, n float64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *CurveMsg) V(j int) float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *CurveMsg) VLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CurveMsg) MutateV(j int, n float64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func CurveMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CurveMsgAddT(builder *flatbuffers.Builder, t flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(t), 0)
}
func CurveMsgStartTVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func CurveMsgAddV(builder *flatbuffers.Builder, v flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(v), 0)
}
func CurveMsgStartVVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func CurveMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
