// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PanelConfigEntryT struct {
	PanelId string `json:"panel_id"`
	Layer string `json:"layer"`
	Cacheable bool `json:"cacheable"`
	MaxCacheCount int64 `json:"max_cache_count"`
	CloseByBack bool `json:"close_by_back"`
}

func (t *PanelConfigEntryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	panelIdOffset := flatbuffers.UOffsetT(0)
	if t.PanelId != "" {
		panelIdOffset = builder.CreateString(t.PanelId)
	}
	layerOffset := flatbuffers.UOffsetT(0)
	if t.Layer != "" {
		layerOffset = builder.CreateString(t.Layer)
	}
	PanelConfigEntryStart(builder)
	PanelConfigEntryAddPanelId(builder, panelIdOffset)
	PanelConfigEntryAddLayer(builder, layerOffset)
	PanelConfigEntryAddCacheable(builder, t.Cacheable)
	PanelConfigEntryAddMaxCacheCount(builder, t.MaxCacheCount)
	PanelConfigEntryAddCloseByBack(builder, t.CloseByBack)
	return PanelConfigEntryEnd(builder)
}

func (rcv *PanelConfigEntry) UnPackTo(t *PanelConfigEntryT) {
	t.PanelId = string(rcv.PanelId())
	t.Layer = string(rcv.Layer())
	t.Cacheable = rcv.Cacheable()
	t.MaxCacheCount = rcv.MaxCacheCount()
	t.CloseByBack = rcv.CloseByBack()
}

func (rcv *PanelConfigEntry) UnPack() *PanelConfigEntryT {
	if rcv == nil {
		return nil
	}
	t := &PanelConfigEntryT{}
	rcv.UnPackTo(t)
	return t
}

type PanelConfigEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsPanelConfigEntry(buf []byte, offset flatbuffers.UOffsetT) *PanelConfigEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PanelConfigEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishPanelConfigEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPanelConfigEntry(buf []byte, offset flatbuffers.UOffsetT) *PanelConfigEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PanelConfigEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPanelConfigEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PanelConfigEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PanelConfigEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PanelConfigEntry) PanelId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PanelConfigEntry) Layer() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PanelConfigEntry) Cacheable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PanelConfigEntry) MutateCacheable(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *PanelConfigEntry) MaxCacheCount() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PanelConfigEntry) MutateMaxCacheCount(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *PanelConfigEntry) CloseByBack() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PanelConfigEntry) MutateCloseByBack(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func PanelConfigEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PanelConfigEntryAddPanelId(builder *flatbuffers.Builder, panelId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(panelId), 0)
}
func PanelConfigEntryAddLayer(builder *flatbuffers.Builder, layer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(layer), 0)
}
func PanelConfigEntryAddCacheable(builder *flatbuffers.Builder, cacheable bool) {
	builder.PrependBoolSlot(2, cacheable, false)
}
func PanelConfigEntryAddMaxCacheCount(builder *flatbuffers.Builder, maxCacheCount int64) {
	builder.PrependInt64Slot(3, maxCacheCount, 0)
}
func PanelConfigEntryAddCloseByBack(builder *flatbuffers.Builder, closeByBack bool) {
	builder.PrependBoolSlot(4, closeByBack, false)
}
func PanelConfigEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
