// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PanelConfigMsgT struct {
	Entries []*PanelConfigEntryT `json:"entries"`
}

func (t *PanelConfigMsgT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	entriesOffset := flatbuffers.UOffsetT(0)
	if t.Entries != nil {
		entriesLength := len(t.Entries)
		entriesOffsets := make([]flatbuffers.UOffsetT, entriesLength)
		for j := 0; j < entriesLength; j++ {
			entriesOffsets[j] = t.Entries[j].Pack(builder)
		}
		PanelConfigMsgStartEntriesVector(builder, entriesLength)
		for j := entriesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(entriesOffsets[j])
		}
		entriesOffset = builder.EndVector(entriesLength)
	}
	PanelConfigMsgStart(builder)
	PanelConfigMsgAddEntries(builder, entriesOffset)
	return PanelConfigMsgEnd(builder)
}

func (rcv *PanelConfigMsg) UnPackTo(t *PanelConfigMsgT) {
	entriesLength := rcv.EntriesLength()
	t.Entries = make([]*PanelConfigEntryT, entriesLength)
	for j := 0; j < entriesLength; j++ {
		x := PanelConfigEntry{}
		rcv.Entries(&x, j)
		t.Entries[j] = x.UnPack()
	}
}

func (rcv *PanelConfigMsg) UnPack() *PanelConfigMsgT {
	if rcv == nil {
		return nil
	}
	t := &PanelConfigMsgT{}
	rcv.UnPackTo(t)
	return t
}

type PanelConfigMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsPanelConfigMsg(buf []byte, offset flatbuffers.UOffsetT) *PanelConfigMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PanelConfigMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishPanelConfigMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPanelConfigMsg(buf []byte, offset flatbuffers.UOffsetT) *PanelConfigMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PanelConfigMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPanelConfigMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PanelConfigMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PanelConfigMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PanelConfigMsg) Entries(obj *PanelConfigEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PanelConfigMsg) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PanelConfigMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PanelConfigMsgAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func PanelConfigMsgStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PanelConfigMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
