// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerConfigMsgT struct {
	SprintToRunTime float32 `json:"sprint_to_run_time"`
	FallSpeedLimit float32 `json:"fall_speed_limit"`
	Gravity float32 `json:"gravity"`
	ColliderHeight float32 `json:"collider_height"`
	ColliderCenterY float32 `json:"collider_center_y"`
	ColliderRadius float32 `json:"collider_radius"`
	StepHeightPercentage float32 `json:"step_height_percentage"`
	VoxelMaxStepHeight float32 `json:"voxel_max_step_height"`
	CameraBackwards []*CameraRecenteringEntryT `json:"camera_backwards"`
	CameraSideways []*CameraRecenteringEntryT `json:"camera_sideways"`
}

func (t *PlayerConfigMsgT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	cameraBackwardsOffset := flatbuffers.UOffsetT(0)
	if t.CameraBackwards != nil {
		cameraBackwardsLength := len(t.CameraBackwards)
		cameraBackwardsOffsets := make([]flatbuffers.UOffsetT, cameraBackwardsLength)
		for j := 0; j < cameraBackwardsLength; j++ {
			cameraBackwardsOffsets[j] = t.CameraBackwards[j].Pack(builder)
		}
		PlayerConfigMsgStartCameraBackwardsVector(builder, cameraBackwardsLength)
		for j := cameraBackwardsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(cameraBackwardsOffsets[j])
		}
		cameraBackwardsOffset = builder.EndVector(cameraBackwardsLength)
	}
	cameraSidewaysOffset := flatbuffers.UOffsetT(0)
	if t.CameraSideways != nil {
		cameraSidewaysLength := len(t.CameraSideways)
		cameraSidewaysOffsets := make([]flatbuffers.UOffsetT, cameraSidewaysLength)
		for j := 0; j < cameraSidewaysLength; j++ {
			cameraSidewaysOffsets[j] = t.CameraSideways[j].Pack(builder)
		}
		PlayerConfigMsgStartCameraSidewaysVector(builder, cameraSidewaysLength)
		for j := cameraSidewaysLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(cameraSidewaysOffsets[j])
		}
		cameraSidewaysOffset = builder.EndVector(cameraSidewaysLength)
	}
	PlayerConfigMsgStart(builder)
	PlayerConfigMsgAddSprintToRunTime(builder, t.SprintToRunTime)
	PlayerConfigMsgAddFallSpeedLimit(builder, t.FallSpeedLimit)
	PlayerConfigMsgAddGravity(builder, t.Gravity)
	PlayerConfigMsgAddColliderHeight(builder, t.ColliderHeight)
	PlayerConfigMsgAddColliderCenterY(builder, t.ColliderCenterY)
	PlayerConfigMsgAddColliderRadius(builder, t.ColliderRadius)
	PlayerConfigMsgAddStepHeightPercentage(builder, t.StepHeightPercentage)
	PlayerConfigMsgAddVoxelMaxStepHeight(builder, t.VoxelMaxStepHeight)
	PlayerConfigMsgAddCameraBackwards(builder, cameraBackwardsOffset)
	PlayerConfigMsgAddCameraSideways(builder, cameraSidewaysOffset)
	return PlayerConfigMsgEnd(builder)
}

func (rcv *PlayerConfigMsg) UnPackTo(t *PlayerConfigMsgT) {
	t.SprintToRunTime = rcv.SprintToRunTime()
	t.FallSpeedLimit = rcv.FallSpeedLimit()
	t.Gravity = rcv.Gravity()
	t.ColliderHeight = rcv.ColliderHeight()
	t.ColliderCenterY = rcv.ColliderCenterY()
	t.ColliderRadius = rcv.ColliderRadius()
	t.StepHeightPercentage = rcv.StepHeightPercentage()
	t.VoxelMaxStepHeight = rcv.VoxelMaxStepHeight()
	cameraBackwardsLength := rcv.CameraBackwardsLength()
	t.CameraBackwards = make([]*CameraRecenteringEntryT, cameraBackwardsLength)
	for j := 0; j < cameraBackwardsLength; j++ {
		x := CameraRecenteringEntry{}
		rcv.CameraBackwards(&x, j)
		t.CameraBackwards[j] = x.UnPack()
	}
	cameraSidewaysLength := rcv.CameraSidewaysLength()
	t.CameraSideways = make([]*CameraRecenteringEntryT, cameraSidewaysLength)
	for j := 0; j < cameraSidewaysLength; j++ {
		x := CameraRecenteringEntry{}
		rcv.CameraSideways(&x, j)
		t.CameraSideways[j] = x.UnPack()
	}
}

func (rcv *PlayerConfigMsg) UnPack() *PlayerConfigMsgT {
	if rcv == nil {
		return nil
	}
	t := &PlayerConfigMsgT{}
	rcv.UnPackTo(t)
	return t
}

type PlayerConfigMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerConfigMsg(buf []byte, offset flatbuffers.UOffsetT) *PlayerConfigMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerConfigMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerConfigMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerConfigMsg(buf []byte, offset flatbuffers.UOffsetT) *PlayerConfigMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerConfigMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerConfigMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerConfigMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerConfigMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerConfigMsg) SprintToRunTime() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerConfigMsg) MutateSprintToRunTime(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *PlayerConfigMsg) FallSpeedLimit() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerConfigMsg) MutateFallSpeedLimit(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *PlayerConfigMsg) Gravity() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerConfigMsg) MutateGravity(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *PlayerConfigMsg) ColliderHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerConfigMsg) MutateColliderHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *PlayerConfigMsg) ColliderCenterY() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerConfigMsg) MutateColliderCenterY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *PlayerConfigMsg) ColliderRadius() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerConfigMsg) MutateColliderRadius(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *PlayerConfigMsg) StepHeightPercentage() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerConfigMsg) MutateStepHeightPercentage(n float32) bool {
	return rcv._tab.MutateFloat32Slot(16, n)
}

func (rcv *PlayerConfigMsg) VoxelMaxStepHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerConfigMsg) MutateVoxelMaxStepHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(18, n)
}

func (rcv *PlayerConfigMsg) CameraBackwards(obj *CameraRecenteringEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlayerConfigMsg) CameraBackwardsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PlayerConfigMsg) CameraSideways(obj *CameraRecenteringEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlayerConfigMsg) CameraSidewaysLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PlayerConfigMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func PlayerConfigMsgAddSprintToRunTime(builder *flatbuffers.Builder, sprintToRunTime float32) {
	builder.PrependFloat32Slot(0, sprintToRunTime, 0.0)
}
func PlayerConfigMsgAddFallSpeedLimit(builder *flatbuffers.Builder, fallSpeedLimit float32) {
	builder.PrependFloat32Slot(1, fallSpeedLimit, 0.0)
}
func PlayerConfigMsgAddGravity(builder *flatbuffers.Builder, gravity float32) {
	builder.PrependFloat32Slot(2, gravity, 0.0)
}
func PlayerConfigMsgAddColliderHeight(builder *flatbuffers.Builder, colliderHeight float32) {
	builder.PrependFloat32Slot(3, colliderHeight, 0.0)
}
func PlayerConfigMsgAddColliderCenterY(builder *flatbuffers.Builder, colliderCenterY float32) {
	builder.PrependFloat32Slot(4, colliderCenterY, 0.0)
}
func PlayerConfigMsgAddColliderRadius(builder *flatbuffers.Builder, colliderRadius float32) {
	builder.PrependFloat32Slot(5, colliderRadius, 0.0)
}
func PlayerConfigMsgAddStepHeightPercentage(builder *flatbuffers.Builder, stepHeightPercentage float32) {
	builder.PrependFloat32Slot(6, stepHeightPercentage, 0.0)
}
func PlayerConfigMsgAddVoxelMaxStepHeight(builder *flatbuffers.Builder, voxelMaxStepHeight float32) {
	builder.PrependFloat32Slot(7, voxelMaxStepHeight, 0.0)
}
func PlayerConfigMsgAddCameraBackwards(builder *flatbuffers.Builder, cameraBackwards flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(cameraBackwards), 0)
}
func PlayerConfigMsgStartCameraBackwardsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlayerConfigMsgAddCameraSideways(builder *flatbuffers.Builder, cameraSideways flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(cameraSideways), 0)
}
func PlayerConfigMsgStartCameraSidewaysVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlayerConfigMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
