// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SceneConfigEntryT struct {
	SceneId string `json:"scene_id"`
	SpawnX float32 `json:"spawn_x"`
	SpawnZ float32 `json:"spawn_z"`
	IsDefault bool `json:"is_default"`
}

func (t *SceneConfigEntryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	sceneIdOffset := flatbuffers.UOffsetT(0)
	if t.SceneId != "" {
		sceneIdOffset = builder.CreateString(t.SceneId)
	}
	SceneConfigEntryStart(builder)
	SceneConfigEntryAddSceneId(builder, sceneIdOffset)
	SceneConfigEntryAddSpawnX(builder, t.SpawnX)
	SceneConfigEntryAddSpawnZ(builder, t.SpawnZ)
	SceneConfigEntryAddIsDefault(builder, t.IsDefault)
	return SceneConfigEntryEnd(builder)
}

func (rcv *SceneConfigEntry) UnPackTo(t *SceneConfigEntryT) {
	t.SceneId = string(rcv.SceneId())
	t.SpawnX = rcv.SpawnX()
	t.SpawnZ = rcv.SpawnZ()
	t.IsDefault = rcv.IsDefault()
}

func (rcv *SceneConfigEntry) UnPack() *SceneConfigEntryT {
	if rcv == nil {
		return nil
	}
	t := &SceneConfigEntryT{}
	rcv.UnPackTo(t)
	return t
}

type SceneConfigEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsSceneConfigEntry(buf []byte, offset flatbuffers.UOffsetT) *SceneConfigEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SceneConfigEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishSceneConfigEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSceneConfigEntry(buf []byte, offset flatbuffers.UOffsetT) *SceneConfigEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SceneConfigEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSceneConfigEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SceneConfigEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SceneConfigEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SceneConfigEntry) SceneId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SceneConfigEntry) SpawnX() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *SceneConfigEntry) MutateSpawnX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *SceneConfigEntry) SpawnZ() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *SceneConfigEntry) MutateSpawnZ(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *SceneConfigEntry) IsDefault() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SceneConfigEntry) MutateIsDefault(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func SceneConfigEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func SceneConfigEntryAddSceneId(builder *flatbuffers.Builder, sceneId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sceneId), 0)
}
func SceneConfigEntryAddSpawnX(builder *flatbuffers.Builder, spawnX float32) {
	builder.PrependFloat32Slot(1, spawnX, 0.0)
}
func SceneConfigEntryAddSpawnZ(builder *flatbuffers.Builder, spawnZ float32) {
	builder.PrependFloat32Slot(2, spawnZ, 0.0)
}
func SceneConfigEntryAddIsDefault(builder *flatbuffers.Builder, isDefault bool) {
	builder.PrependBoolSlot(3, isDefault, false)
}
func SceneConfigEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
