// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SceneConfigMsgT struct {
	Entries []*SceneConfigEntryT `json:"entries"`
}

func (t *SceneConfigMsgT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	entriesOffset := flatbuffers.UOffsetT(0)
	if t.Entries != nil {
		entriesLength := len(t.Entries)
		entriesOffsets := make([]flatbuffers.UOffsetT, entriesLength)
		for j := 0; j < entriesLength; j++ {
			entriesOffsets[j] = t.Entries[j].Pack(builder)
		}
		SceneConfigMsgStartEntriesVector(builder, entriesLength)
		for j := entriesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(entriesOffsets[j])
		}
		entriesOffset = builder.EndVector(entriesLength)
	}
	SceneConfigMsgStart(builder)
	SceneConfigMsgAddEntries(builder, entriesOffset)
	return SceneConfigMsgEnd(builder)
}

func (rcv *SceneConfigMsg) UnPackTo(t *SceneConfigMsgT) {
	entriesLength := rcv.EntriesLength()
	t.Entries = make([]*SceneConfigEntryT, entriesLength)
	for j := 0; j < entriesLength; j++ {
		x := SceneConfigEntry{}
		rcv.Entries(&x, j)
		t.Entries[j] = x.UnPack()
	}
}

func (rcv *SceneConfigMsg) UnPack() *SceneConfigMsgT {
	if rcv == nil {
		return nil
	}
	t := &SceneConfigMsgT{}
	rcv.UnPackTo(t)
	return t
}

type SceneConfigMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsSceneConfigMsg(buf []byte, offset flatbuffers.UOffsetT) *SceneConfigMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SceneConfigMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishSceneConfigMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSceneConfigMsg(buf []byte, offset flatbuffers.UOffsetT) *SceneConfigMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SceneConfigMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSceneConfigMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SceneConfigMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SceneConfigMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SceneConfigMsg) Entries(obj *SceneConfigEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SceneConfigMsg) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SceneConfigMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SceneConfigMsgAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func SceneConfigMsgStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SceneConfigMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
