// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StateConfigEntryT struct {
	State string `json:"state"`
	AnimationName string `json:"animation_name"`
	CurveX string `json:"curve_x"`
	CurveY string `json:"curve_y"`
	CurveZ string `json:"curve_z"`
	DurationSeconds float32 `json:"duration_seconds"`
	TotalTicks int64 `json:"total_ticks"`
	Loop int64 `json:"loop"`
	MaxPerFrame float32 `json:"max_per_frame"`
}

func (t *StateConfigEntryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	stateOffset := flatbuffers.UOffsetT(0)
	if t.State != "" {
		stateOffset = builder.CreateString(t.State)
	}
	animationNameOffset := flatbuffers.UOffsetT(0)
	if t.AnimationName != "" {
		animationNameOffset = builder.CreateString(t.AnimationName)
	}
	curveXOffset := flatbuffers.UOffsetT(0)
	if t.CurveX != "" {
		curveXOffset = builder.CreateString(t.CurveX)
	}
	curveYOffset := flatbuffers.UOffsetT(0)
	if t.CurveY != "" {
		curveYOffset = builder.CreateString(t.CurveY)
	}
	curveZOffset := flatbuffers.UOffsetT(0)
	if t.CurveZ != "" {
		curveZOffset = builder.CreateString(t.CurveZ)
	}
	StateConfigEntryStart(builder)
	StateConfigEntryAddState(builder, stateOffset)
	StateConfigEntryAddAnimationName(builder, animationNameOffset)
	StateConfigEntryAddCurveX(builder, curveXOffset)
	StateConfigEntryAddCurveY(builder, curveYOffset)
	StateConfigEntryAddCurveZ(builder, curveZOffset)
	StateConfigEntryAddDurationSeconds(builder, t.DurationSeconds)
	StateConfigEntryAddTotalTicks(builder, t.TotalTicks)
	StateConfigEntryAddLoop(builder, t.Loop)
	StateConfigEntryAddMaxPerFrame(builder, t.MaxPerFrame)
	return StateConfigEntryEnd(builder)
}

func (rcv *StateConfigEntry) UnPackTo(t *StateConfigEntryT) {
	t.State = string(rcv.State())
	t.AnimationName = string(rcv.AnimationName())
	t.CurveX = string(rcv.CurveX())
	t.CurveY = string(rcv.CurveY())
	t.CurveZ = string(rcv.CurveZ())
	t.DurationSeconds = rcv.DurationSeconds()
	t.TotalTicks = rcv.TotalTicks()
	t.Loop = rcv.Loop()
	t.MaxPerFrame = rcv.MaxPerFrame()
}

func (rcv *StateConfigEntry) UnPack() *StateConfigEntryT {
	if rcv == nil {
		return nil
	}
	t := &StateConfigEntryT{}
	rcv.UnPackTo(t)
	return t
}

type StateConfigEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsStateConfigEntry(buf []byte, offset flatbuffers.UOffsetT) *StateConfigEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StateConfigEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishStateConfigEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStateConfigEntry(buf []byte, offset flatbuffers.UOffsetT) *StateConfigEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StateConfigEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStateConfigEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StateConfigEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StateConfigEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StateConfigEntry) State() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StateConfigEntry) AnimationName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StateConfigEntry) CurveX() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StateConfigEntry) CurveY() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StateConfigEntry) CurveZ() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StateConfigEntry) DurationSeconds() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StateConfigEntry) MutateDurationSeconds(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *StateConfigEntry) TotalTicks() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StateConfigEntry) MutateTotalTicks(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *StateConfigEntry) Loop() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StateConfigEntry) MutateLoop(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *StateConfigEntry) MaxPerFrame() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StateConfigEntry) MutateMaxPerFrame(n float32) bool {
	return rcv._tab.MutateFloat32Slot(20, n)
}

func StateConfigEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func StateConfigEntryAddState(builder *flatbuffers.Builder, state flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(state), 0)
}
func StateConfigEntryAddAnimationName(builder *flatbuffers.Builder, animationName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(animationName), 0)
}
func StateConfigEntryAddCurveX(builder *flatbuffers.Builder, curveX flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(curveX), 0)
}
func StateConfigEntryAddCurveY(builder *flatbuffers.Builder, curveY flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(curveY), 0)
}
func StateConfigEntryAddCurveZ(builder *flatbuffers.Builder, curveZ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(curveZ), 0)
}
func StateConfigEntryAddDurationSeconds(builder *flatbuffers.Builder, durationSeconds float32) {
	builder.PrependFloat32Slot(5, durationSeconds, 0.0)
}
func StateConfigEntryAddTotalTicks(builder *flatbuffers.Builder, totalTicks int64) {
	builder.PrependInt64Slot(6, totalTicks, 0)
}
func StateConfigEntryAddLoop(builder *flatbuffers.Builder, loop int64) {
	builder.PrependInt64Slot(7, loop, 0)
}
func StateConfigEntryAddMaxPerFrame(builder *flatbuffers.Builder, maxPerFrame float32) {
	builder.PrependFloat32Slot(8, maxPerFrame, 0.0)
}
func StateConfigEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
