// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StateConfigMsgT struct {
	Entries []*StateConfigEntryT `json:"entries"`
}

func (t *StateConfigMsgT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	entriesOffset := flatbuffers.UOffsetT(0)
	if t.Entries != nil {
		entriesLength := len(t.Entries)
		entriesOffsets := make([]flatbuffers.UOffsetT, entriesLength)
		for j := 0; j < entriesLength; j++ {
			entriesOffsets[j] = t.Entries[j].Pack(builder)
		}
		StateConfigMsgStartEntriesVector(builder, entriesLength)
		for j := entriesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(entriesOffsets[j])
		}
		entriesOffset = builder.EndVector(entriesLength)
	}
	StateConfigMsgStart(builder)
	StateConfigMsgAddEntries(builder, entriesOffset)
	return StateConfigMsgEnd(builder)
}

func (rcv *StateConfigMsg) UnPackTo(t *StateConfigMsgT) {
	entriesLength := rcv.EntriesLength()
	t.Entries = make([]*StateConfigEntryT, entriesLength)
	for j := 0; j < entriesLength; j++ {
		x := StateConfigEntry{}
		rcv.Entries(&x, j)
		t.Entries[j] = x.UnPack()
	}
}

func (rcv *StateConfigMsg) UnPack() *StateConfigMsgT {
	if rcv == nil {
		return nil
	}
	t := &StateConfigMsgT{}
	rcv.UnPackTo(t)
	return t
}

type StateConfigMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsStateConfigMsg(buf []byte, offset flatbuffers.UOffsetT) *StateConfigMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StateConfigMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishStateConfigMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStateConfigMsg(buf []byte, offset flatbuffers.UOffsetT) *StateConfigMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StateConfigMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStateConfigMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StateConfigMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StateConfigMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StateConfigMsg) Entries(obj *StateConfigEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *StateConfigMsg) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func StateConfigMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StateConfigMsgAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func StateConfigMsgStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StateConfigMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
