// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransitionEntryT struct {
	Source string `json:"source"`
	AllowedTargets []string `json:"allowed_targets"`
}

func (t *TransitionEntryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	sourceOffset := flatbuffers.UOffsetT(0)
	if t.Source != "" {
		sourceOffset = builder.CreateString(t.Source)
	}
	allowedTargetsOffset := flatbuffers.UOffsetT(0)
	if t.AllowedTargets != nil {
		allowedTargetsLength := len(t.AllowedTargets)
		allowedTargetsOffsets := make([]flatbuffers.UOffsetT, allowedTargetsLength)
		for j := 0; j < allowedTargetsLength; j++ {
			allowedTargetsOffsets[j] = builder.CreateString(t.AllowedTargets[j])
		}
		TransitionEntryStartAllowedTargetsVector(builder, allowedTargetsLength)
		for j := allowedTargetsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(allowedTargetsOffsets[j])
		}
		allowedTargetsOffset = builder.EndVector(allowedTargetsLength)
	}
	TransitionEntryStart(builder)
	TransitionEntryAddSource(builder, sourceOffset)
	TransitionEntryAddAllowedTargets(builder, allowedTargetsOffset)
	return TransitionEntryEnd(builder)
}

func (rcv *TransitionEntry) UnPackTo(t *TransitionEntryT) {
	t.Source = string(rcv.Source())
	allowedTargetsLength := rcv.AllowedTargetsLength()
	t.AllowedTargets = make([]string, allowedTargetsLength)
	for j := 0; j < allowedTargetsLength; j++ {
		t.AllowedTargets[j] = string(rcv.AllowedTargets(j))
	}
}

func (rcv *TransitionEntry) UnPack() *TransitionEntryT {
	if rcv == nil {
		return nil
	}
	t := &TransitionEntryT{}
	rcv.UnPackTo(t)
	return t
}

type TransitionEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsTransitionEntry(buf []byte, offset flatbuffers.UOffsetT) *TransitionEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransitionEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransitionEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransitionEntry(buf []byte, offset flatbuffers.UOffsetT) *TransitionEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransitionEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransitionEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransitionEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransitionEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransitionEntry) Source() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransitionEntry) AllowedTargets(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *TransitionEntry) AllowedTargetsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TransitionEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TransitionEntryAddSource(builder *flatbuffers.Builder, source flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(source), 0)
}
func TransitionEntryAddAllowedTargets(builder *flatbuffers.Builder, allowedTargets flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(allowedTargets), 0)
}
func TransitionEntryStartAllowedTargetsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TransitionEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
