// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransitionTableMsgT struct {
	Entries []*TransitionEntryT `json:"entries"`
}

func (t *TransitionTableMsgT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	entriesOffset := flatbuffers.UOffsetT(0)
	if t.Entries != nil {
		entriesLength := len(t.Entries)
		entriesOffsets := make([]flatbuffers.UOffsetT, entriesLength)
		for j := 0; j < entriesLength; j++ {
			entriesOffsets[j] = t.Entries[j].Pack(builder)
		}
		TransitionTableMsgStartEntriesVector(builder, entriesLength)
		for j := entriesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(entriesOffsets[j])
		}
		entriesOffset = builder.EndVector(entriesLength)
	}
	TransitionTableMsgStart(builder)
	TransitionTableMsgAddEntries(builder, entriesOffset)
	return TransitionTableMsgEnd(builder)
}

func (rcv *TransitionTableMsg) UnPackTo(t *TransitionTableMsgT) {
	entriesLength := rcv.EntriesLength()
	t.Entries = make([]*TransitionEntryT, entriesLength)
	for j := 0; j < entriesLength; j++ {
		x := TransitionEntry{}
		rcv.Entries(&x, j)
		t.Entries[j] = x.UnPack()
	}
}

func (rcv *TransitionTableMsg) UnPack() *TransitionTableMsgT {
	if rcv == nil {
		return nil
	}
	t := &TransitionTableMsgT{}
	rcv.UnPackTo(t)
	return t
}

type TransitionTableMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsTransitionTableMsg(buf []byte, offset flatbuffers.UOffsetT) *TransitionTableMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransitionTableMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransitionTableMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransitionTableMsg(buf []byte, offset flatbuffers.UOffsetT) *TransitionTableMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransitionTableMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransitionTableMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransitionTableMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransitionTableMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransitionTableMsg) Entries(obj *TransitionEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TransitionTableMsg) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TransitionTableMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TransitionTableMsgAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func TransitionTableMsgStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TransitionTableMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
